I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'D:\\other stuff\\renpy\\project fantasy\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\other stuff\renpy\renpy-7.1.1-sdk\renpy\bootstrap.py", line 313, in bootstrap
    renpy.main.main()
  File "D:\other stuff\renpy\renpy-7.1.1-sdk\renpy\main.py", line 469, in main
    renpy.dump.dump(False)
  File "D:\other stuff\renpy\renpy-7.1.1-sdk\renpy\dump.py", line 253, in dump
    os.unlink(args.json_dump)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'D:\\other stuff\\renpy\\project fantasy\\game\\saves\\navigation.json'

Windows-8-6.2.9200
Ren'Py 7.1.1.929
project fantasy alpha 1.0
Wed Nov 14 00:51:44 2018
